module xterra {
    module msg {
        module dds_ {
            struct PowerData_ {
                float voltage;
                float current;
                float temperature;
                float energy;
            };
        };
    };
};
