module xterra {
    module msg {
        module dds_ {
            struct Quaternion_ {
                float x;
                float y;
                float z;
                float w;
            };
        };
    };
};
